export const timezone = [
  {
    id: 1,
    value: 'Dateline Standard Time',
    abbr: 'DST',
    offset: -12,
    isdst: 0,
    text: '(UTC-12:00) International Date Line West',
    utc: 'Etc/GMT+12',
  },
  {
    id: 2,
    value: 'UTC-11',
    abbr: 'U',
    offset: -11,
    isdst: 0,
    text: '(UTC-11:00) Coordinated Universal Time-11',
    utc: 'Etc/GMT+11',
  },
  {
    id: 3,
    value: 'Hawaiian Standard Time',
    abbr: 'HST',
    offset: -10,
    isdst: 0,
    text: '(UTC-10:00) Hawaii',
    utc: 'Etc/GMT+10',
  },
  {
    id: 4,
    value: 'Alaskan Standard Time',
    abbr: 'AKDT',
    offset: -8,
    isdst: 1,
    text: '(UTC-09:00) Alaska',
    utc: 'America/Anchorage',
  },
  {
    id: 5,
    value: 'Pacific Standard Time (Mexico)',
    abbr: 'PDT',
    offset: -7,
    isdst: 1,
    text: '(UTC-08:00) Baja California',
    utc: 'America/Santa_Isabel',
  },
  {
    id: 6,
    value: 'Pacific Daylight Time',
    abbr: 'PDT',
    offset: -7,
    isdst: 1,
    text: '(UTC-07:00) Pacific Daylight Time (US & Canada)',
    utc: 'America/Dawson',
  },
  {
    id: 7,
    value: 'Pacific Standard Time',
    abbr: 'PST',
    offset: -8,
    isdst: 0,
    text: '(UTC-08:00) Pacific Standard Time (US & Canada)',
    utc: 'America/Dawson',
  },
  {
    id: 8,
    value: 'US Mountain Standard Time',
    abbr: 'UMST',
    offset: -7,
    isdst: 0,
    text: '(UTC-07:00) Arizona',
    utc: 'America/Creston',
  },
  {
    id: 9,
    value: 'Mountain Standard Time (Mexico)',
    abbr: 'MDT',
    offset: -6,
    isdst: 1,
    text: '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
    utc: 'America/Chihuahua',
  },
  {
    id: 10,
    value: 'Mountain Standard Time',
    abbr: 'MDT',
    offset: -6,
    isdst: 1,
    text: '(UTC-07:00) Mountain Time (US & Canada)',
    utc: 'America/Boise',
  },
  {
    id: 11,
    value: 'Central America Standard Time',
    abbr: 'CAST',
    offset: -6,
    isdst: 0,
    text: '(UTC-06:00) Central America',
    utc: 'America/Belize',
  },
  {
    id: 12,
    value: 'Central Standard Time',
    abbr: 'CDT',
    offset: -5,
    isdst: 1,
    text: '(UTC-06:00) Central Time (US & Canada)',
    utc: 'America/Chicago',
  },
  {
    id: 13,
    value: 'Central Standard Time (Mexico)',
    abbr: 'CDT',
    offset: -5,
    isdst: 1,
    text: '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
    utc: 'America/Bahia_Banderas',
  },
  {
    id: 14,
    value: 'Canada Central Standard Time',
    abbr: 'CCST',
    offset: -6,
    isdst: 0,
    text: '(UTC-06:00) Saskatchewan',
    utc: 'America/Regina',
  },
  {
    id: 15,
    value: 'SA Pacific Standard Time',
    abbr: 'SPST',
    offset: -5,
    isdst: 0,
    text: '(UTC-05:00) Bogota, Lima, Quito',
    utc: 'America/Bogota',
  },
  {
    id: 16,
    value: 'Eastern Standard Time',
    abbr: 'EDT',
    offset: -4,
    isdst: 1,
    text: '(UTC-05:00) Eastern Time (US & Canada)',
    utc: 'America/Detroit',
  },
  {
    id: 17,
    value: 'US Eastern Standard Time',
    abbr: 'UEDT',
    offset: -4,
    isdst: 1,
    text: '(UTC-05:00) Indiana (East)',
    utc: 'America/Indiana/Marengo',
  },
  {
    id: 18,
    value: 'Venezuela Standard Time',
    abbr: 'VST',
    offset: -5,
    isdst: 0,
    text: '(UTC-04:30) Caracas',
    utc: 'America/Caracas',
  },
  {
    id: 19,
    value: 'Paraguay Standard Time',
    abbr: 'PYT',
    offset: -4,
    isdst: 0,
    text: '(UTC-04:00) Asuncion',
    utc: 'America/Asuncion',
  },
  {
    id: 20,
    value: 'Atlantic Standard Time',
    abbr: 'ADT',
    offset: -3,
    isdst: 1,
    text: '(UTC-04:00) Atlantic Time (Canada)',
    utc: 'America/Glace_Bay',
  },
  {
    id: 21,
    value: 'Central Brazilian Standard Time',
    abbr: 'CBST',
    offset: -4,
    isdst: 0,
    text: '(UTC-04:00) Cuiaba',
    utc: 'America/Campo_Grande',
  },
  {
    id: 22,
    value: 'SA Western Standard Time',
    abbr: 'SWST',
    offset: -4,
    isdst: 0,
    text: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
    utc: 'America/Anguilla',
  },
  {
    id: 23,
    value: 'Pacific SA Standard Time',
    abbr: 'PSST',
    offset: -4,
    isdst: 0,
    text: '(UTC-04:00) Santiago',
    utc: 'America/Santiago',
  },
  {
    id: 24,
    value: 'Newfoundland Standard Time',
    abbr: 'NDT',
    offset: -3,
    isdst: 1,
    text: '(UTC-03:30) Newfoundland',
    utc: 'America/St_Johns',
  },
  {
    id: 25,
    value: 'E. South America Standard Time',
    abbr: 'ESAST',
    offset: -3,
    isdst: 0,
    text: '(UTC-03:00) Brasilia',
    utc: 'America/Sao_Paulo',
  },
  {
    id: 26,
    value: 'Argentina Standard Time',
    abbr: 'AST',
    offset: -3,
    isdst: 0,
    text: '(UTC-03:00) Buenos Aires',
    utc: 'America/Argentina/La_Rioja',
  },
  {
    id: 27,
    value: 'SA Eastern Standard Time',
    abbr: 'SEST',
    offset: -3,
    isdst: 0,
    text: '(UTC-03:00) Cayenne, Fortaleza',
    utc: 'America/Araguaina',
  },
  {
    id: 28,
    value: 'Greenland Standard Time',
    abbr: 'GDT',
    offset: -3,
    isdst: 1,
    text: '(UTC-03:00) Greenland',
    utc: 'America/Godthab',
  },
  {
    id: 29,
    value: 'Montevideo Standard Time',
    abbr: 'MST',
    offset: -3,
    isdst: 0,
    text: '(UTC-03:00) Montevideo',
    utc: 'America/Montevideo',
  },
  {
    id: 30,
    value: 'Bahia Standard Time',
    abbr: 'BST',
    offset: -3,
    isdst: 0,
    text: '(UTC-03:00) Salvador',
    utc: 'America/Bahia',
  },
  {
    id: 31,
    value: 'UTC-02',
    abbr: 'U',
    offset: -2,
    isdst: 0,
    text: '(UTC-02:00) Coordinated Universal Time-02',
    utc: 'America/Noronha',
  },
  {
    id: 32,
    value: 'Azores Standard Time',
    abbr: 'ADT',
    offset: 0,
    isdst: 1,
    text: '(UTC-01:00) Azores',
    utc: 'America/Scoresbysund',
  },
  {
    id: 33,
    value: 'Cape Verde Standard Time',
    abbr: 'CVST',
    offset: -1,
    isdst: 0,
    text: '(UTC-01:00) Cape Verde Is.',
    utc: 'Atlantic/Cape_Verde',
  },
  {
    id: 34,
    value: 'Morocco Standard Time',
    abbr: 'MDT',
    offset: 1,
    isdst: 1,
    text: '(UTC) Casablanca',
    utc: 'Africa/Casablanca',
  },
  {
    id: 35,
    value: 'UTC',
    abbr: 'UTC',
    offset: 0,
    isdst: 0,
    text: '(UTC) Coordinated Universal Time',
    utc: 'America/Danmarkshavn',
  },
  {
    id: 36,
    value: 'Greenwich Mean Time',
    abbr: 'GMT',
    offset: 0,
    isdst: 0,
    text: '(UTC) Edinburgh, London',
    utc: 'Europe/Isle_of_Man',
  },
  {
    id: 37,
    value: 'British Summer Time',
    abbr: 'BST',
    offset: 1,
    isdst: 1,
    text: '(UTC+01:00) Edinburgh, London',
    utc: 'Europe/Isle_of_Man',
  },
  {
    id: 38,
    value: 'GMT Standard Time',
    abbr: 'GDT',
    offset: 1,
    isdst: 1,
    text: '(UTC) Dublin, Lisbon',
    utc: 'Atlantic/Canary',
  },
  {
    id: 39,
    value: 'Greenwich Standard Time',
    abbr: 'GST',
    offset: 0,
    isdst: 0,
    text: '(UTC) Monrovia, Reykjavik',
    utc: 'Africa/Abidjan',
  },
  {
    id: 40,
    value: 'W. Europe Standard Time',
    abbr: 'WEDT',
    offset: 2,
    isdst: 1,
    text: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    utc: 'Arctic/Longyearbyen',
  },
  {
    id: 41,
    value: 'Central Europe Standard Time',
    abbr: 'CEDT',
    offset: 2,
    isdst: 1,
    text: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    utc: 'Europe/Belgrade',
  },
  {
    id: 42,
    value: 'Romance Standard Time',
    abbr: 'RDT',
    offset: 2,
    isdst: 1,
    text: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
    utc: 'Africa/Ceuta',
  },
  {
    id: 43,
    value: 'Central European Standard Time',
    abbr: 'CEDT',
    offset: 2,
    isdst: 1,
    text: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    utc: 'Europe/Sarajevo',
  },
  {
    id: 44,
    value: 'W. Central Africa Standard Time',
    abbr: 'WCAST',
    offset: 1,
    isdst: 0,
    text: '(UTC+01:00) West Central Africa',
    utc: 'Africa/Algiers',
  },
  {
    id: 45,
    value: 'Namibia Standard Time',
    abbr: 'NST',
    offset: 1,
    isdst: 0,
    text: '(UTC+01:00) Windhoek',
    utc: 'Africa/Windhoek',
  },
  {
    id: 46,
    value: 'GTB Standard Time',
    abbr: 'GDT',
    offset: 3,
    isdst: 1,
    text: '(UTC+02:00) Athens, Bucharest',
    utc: 'Asia/Nicosia',
  },
  {
    id: 47,
    value: 'Middle East Standard Time',
    abbr: 'MEDT',
    offset: 3,
    isdst: 1,
    text: '(UTC+02:00) Beirut',
    utc: 'Asia/Beirut',
  },
  {
    id: 48,
    value: 'Egypt Standard Time',
    abbr: 'EST',
    offset: 2,
    isdst: 0,
    text: '(UTC+02:00) Cairo',
    utc: 'Africa/Cairo',
  },
  {
    id: 49,
    value: 'Syria Standard Time',
    abbr: 'SDT',
    offset: 3,
    isdst: 1,
    text: '(UTC+02:00) Damascus',
    utc: 'Asia/Damascus',
  },
  {
    id: 50,
    value: 'E. Europe Standard Time',
    abbr: 'EEDT',
    offset: 3,
    isdst: 1,
    text: '(UTC+02:00) E. Europe',
    utc: 'Asia/Nicosia',
  },
  {
    id: 51,
    value: 'South Africa Standard Time',
    abbr: 'SAST',
    offset: 2,
    isdst: 0,
    text: '(UTC+02:00) Harare, Pretoria',
    utc: 'Africa/Blantyre',
  },
  {
    id: 52,
    value: 'FLE Standard Time',
    abbr: 'FDT',
    offset: 3,
    isdst: 1,
    text: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    utc: 'Europe/Helsinki',
  },
  {
    id: 53,
    value: 'Turkey Standard Time',
    abbr: 'TDT',
    offset: 3,
    isdst: 0,
    text: '(UTC+03:00) Istanbul',
    utc: 'Europe/Istanbul',
  },
  {
    id: 54,
    value: 'Israel Standard Time',
    abbr: 'JDT',
    offset: 3,
    isdst: 1,
    text: '(UTC+02:00) Jerusalem',
    utc: 'Asia/Jerusalem',
  },
  {
    id: 55,
    value: 'Libya Standard Time',
    abbr: 'LST',
    offset: 2,
    isdst: 0,
    text: '(UTC+02:00) Tripoli',
    utc: 'Africa/Tripoli',
  },
  {
    id: 56,
    value: 'Jordan Standard Time',
    abbr: 'JST',
    offset: 3,
    isdst: 0,
    text: '(UTC+03:00) Amman',
    utc: 'Asia/Amman',
  },
  {
    id: 57,
    value: 'Arabic Standard Time',
    abbr: 'AST',
    offset: 3,
    isdst: 0,
    text: '(UTC+03:00) Baghdad',
    utc: 'Asia/Baghdad',
  },
  {
    id: 58,
    value: 'Kaliningrad Standard Time',
    abbr: 'KST',
    offset: 3,
    isdst: 0,
    text: '(UTC+03:00) Kaliningrad, Minsk',
    utc: 'Europe/Kaliningrad',
  },
  {
    id: 59,
    value: 'Arab Standard Time',
    abbr: 'AST',
    offset: 3,
    isdst: 0,
    text: '(UTC+03:00) Kuwait, Riyadh',
    utc: 'Asia/Aden',
  },
  {
    id: 60,
    value: 'E. Africa Standard Time',
    abbr: 'EAST',
    offset: 3,
    isdst: 0,
    text: '(UTC+03:00) Nairobi',
    utc: 'Africa/Addis_Ababa',
  },
  {
    id: 61,
    value: 'Moscow Standard Time',
    abbr: 'MSK',
    offset: 3,
    isdst: 0,
    text: '(UTC+03:00) Moscow, St. Petersburg, Volgograd',
    utc: 'Europe/Kirov',
  },
  {
    id: 62,
    value: 'Samara Time',
    abbr: 'SAMT',
    offset: 4,
    isdst: 0,
    text: '(UTC+04:00) Samara, Ulyanovsk, Saratov',
    utc: 'Europe/Astrakhan',
  },
  {
    id: 63,
    value: 'Iran Standard Time',
    abbr: 'IDT',
    offset: 5,
    isdst: 1,
    text: '(UTC+03:30) Tehran',
    utc: 'Asia/Tehran',
  },
  {
    id: 64,
    value: 'Arabian Standard Time',
    abbr: 'AST',
    offset: 4,
    isdst: 0,
    text: '(UTC+04:00) Abu Dhabi, Muscat',
    utc: 'Asia/Dubai',
  },
  {
    id: 65,
    value: 'Azerbaijan Standard Time',
    abbr: 'ADT',
    offset: 5,
    isdst: 1,
    text: '(UTC+04:00) Baku',
    utc: 'Asia/Baku',
  },
  {
    id: 66,
    value: 'Mauritius Standard Time',
    abbr: 'MST',
    offset: 4,
    isdst: 0,
    text: '(UTC+04:00) Port Louis',
    utc: 'Indian/Mahe',
  },
  {
    id: 67,
    value: 'Georgian Standard Time',
    abbr: 'GET',
    offset: 4,
    isdst: 0,
    text: '(UTC+04:00) Tbilisi',
    utc: 'Asia/Tbilisi',
  },
  {
    id: 68,
    value: 'Caucasus Standard Time',
    abbr: 'CST',
    offset: 4,
    isdst: 0,
    text: '(UTC+04:00) Yerevan',
    utc: 'Asia/Yerevan',
  },
  {
    id: 69,
    value: 'Afghanistan Standard Time',
    abbr: 'AST',
    offset: 5,
    isdst: 0,
    text: '(UTC+04:30) Kabul',
    utc: 'Asia/Kabul',
  },
  {
    id: 70,
    value: 'West Asia Standard Time',
    abbr: 'WAST',
    offset: 5,
    isdst: 0,
    text: '(UTC+05:00) Ashgabat, Tashkent',
    utc: 'Antarctica/Mawson',
  },
  {
    id: 71,
    value: 'Yekaterinburg Time',
    abbr: 'YEKT',
    offset: 5,
    isdst: 0,
    text: '(UTC+05:00) Yekaterinburg',
    utc: 'Asia/Yekaterinburg',
  },
  {
    id: 72,
    value: 'Pakistan Standard Time',
    abbr: 'PKT',
    offset: 5,
    isdst: 0,
    text: '(UTC+05:00) Islamabad, Karachi',
    utc: 'Asia/Karachi',
  },
  {
    id: 73,
    value: 'India Standard Time',
    abbr: 'IST',
    offset: 6,
    isdst: 0,
    text: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    utc: 'Asia/Kolkata',
  },
  {
    id: 74,
    value: 'Sri Lanka Standard Time',
    abbr: 'SLST',
    offset: 6,
    isdst: 0,
    text: '(UTC+05:30) Sri Jayawardenepura',
    utc: 'Asia/Colombo',
  },
  {
    id: 75,
    value: 'Nepal Standard Time',
    abbr: 'NST',
    offset: 6,
    isdst: 0,
    text: '(UTC+05:45) Kathmandu',
    utc: 'Asia/Kathmandu',
  },
  {
    id: 76,
    value: 'Central Asia Standard Time',
    abbr: 'CAST',
    offset: 6,
    isdst: 0,
    text: '(UTC+06:00) Astana',
    utc: 'Antarctica/Vostok',
  },
  {
    id: 77,
    value: 'Bangladesh Standard Time',
    abbr: 'BST',
    offset: 6,
    isdst: 0,
    text: '(UTC+06:00) Dhaka',
    utc: 'Asia/Dhaka',
  },
  {
    id: 78,
    value: 'Myanmar Standard Time',
    abbr: 'MST',
    offset: 7,
    isdst: 0,
    text: '(UTC+06:30) Yangon (Rangoon)',
    utc: 'Asia/Rangoon',
  },
  {
    id: 79,
    value: 'SE Asia Standard Time',
    abbr: 'SAST',
    offset: 7,
    isdst: 0,
    text: '(UTC+07:00) Bangkok, Hanoi, Jakarta',
    utc: 'Antarctica/Davis',
  },
  {
    id: 80,
    value: 'N. Central Asia Standard Time',
    abbr: 'NCAST',
    offset: 7,
    isdst: 0,
    text: '(UTC+07:00) Novosibirsk',
    utc: 'Asia/Novokuznetsk',
  },
  {
    id: 81,
    value: 'China Standard Time',
    abbr: 'CST',
    offset: 8,
    isdst: 0,
    text: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    utc: 'Asia/Hong_Kong',
  },
  {
    id: 82,
    value: 'North Asia Standard Time',
    abbr: 'NAST',
    offset: 8,
    isdst: 0,
    text: '(UTC+08:00) Krasnoyarsk',
    utc: 'Asia/Krasnoyarsk',
  },
  {
    id: 83,
    value: 'Singapore Standard Time',
    abbr: 'MPST',
    offset: 8,
    isdst: 0,
    text: '(UTC+08:00) Kuala Lumpur, Singapore',
    utc: 'Asia/Brunei',
  },
  {
    id: 84,
    value: 'W. Australia Standard Time',
    abbr: 'WAST',
    offset: 8,
    isdst: 0,
    text: '(UTC+08:00) Perth',
    utc: 'Antarctica/Casey',
  },
  {
    id: 85,
    value: 'Taipei Standard Time',
    abbr: 'TST',
    offset: 8,
    isdst: 0,
    text: '(UTC+08:00) Taipei',
    utc: 'Asia/Taipei',
  },
  {
    id: 86,
    value: 'Ulaanbaatar Standard Time',
    abbr: 'UST',
    offset: 8,
    isdst: 0,
    text: '(UTC+08:00) Ulaanbaatar',
    utc: 'Asia/Choibalsan',
  },
  {
    id: 87,
    value: 'North Asia East Standard Time',
    abbr: 'NAEST',
    offset: 8,
    isdst: 0,
    text: '(UTC+08:00) Irkutsk',
    utc: 'Asia/Irkutsk',
  },
  {
    id: 88,
    value: 'Japan Standard Time',
    abbr: 'JST',
    offset: 9,
    isdst: 0,
    text: '(UTC+09:00) Osaka, Sapporo, Tokyo',
    utc: 'Asia/Dili',
  },
  {
    id: 89,
    value: 'Korea Standard Time',
    abbr: 'KST',
    offset: 9,
    isdst: 0,
    text: '(UTC+09:00) Seoul',
    utc: 'Asia/Pyongyang',
  },
  {
    id: 90,
    value: 'Cen. Australia Standard Time',
    abbr: 'CAST',
    offset: 10,
    isdst: 0,
    text: '(UTC+09:30) Adelaide',
    utc: 'Australia/Adelaide',
  },
  {
    id: 91,
    value: 'AUS Central Standard Time',
    abbr: 'ACST',
    offset: 10,
    isdst: 0,
    text: '(UTC+09:30) Darwin',
    utc: 'Australia/Darwin',
  },
  {
    id: 92,
    value: 'E. Australia Standard Time',
    abbr: 'EAST',
    offset: 10,
    isdst: 0,
    text: '(UTC+10:00) Brisbane',
    utc: 'Australia/Brisbane',
  },
  {
    id: 93,
    value: 'AUS Eastern Standard Time',
    abbr: 'AEST',
    offset: 10,
    isdst: 0,
    text: '(UTC+10:00) Canberra, Melbourne, Sydney',
    utc: 'Australia/Melbourne',
  },
  {
    id: 94,
    value: 'West Pacific Standard Time',
    abbr: 'WPST',
    offset: 10,
    isdst: 0,
    text: '(UTC+10:00) Guam, Port Moresby',
    utc: 'Antarctica/DumontDUrville',
  },
  {
    id: 95,
    value: 'Tasmania Standard Time',
    abbr: 'TST',
    offset: 10,
    isdst: 0,
    text: '(UTC+10:00) Hobart',
    utc: 'Australia/Currie',
  },
  {
    id: 96,
    value: 'Yakutsk Standard Time',
    abbr: 'YST',
    offset: 9,
    isdst: 0,
    text: '(UTC+09:00) Yakutsk',
    utc: 'Asia/Chita',
  },
  {
    id: 97,
    value: 'Central Pacific Standard Time',
    abbr: 'CPST',
    offset: 11,
    isdst: 0,
    text: '(UTC+11:00) Solomon Is., New Caledonia',
    utc: 'Antarctica/Macquarie',
  },
  {
    id: 98,
    value: 'Vladivostok Standard Time',
    abbr: 'VST',
    offset: 11,
    isdst: 0,
    text: '(UTC+11:00) Vladivostok',
    utc: 'Asia/Sakhalin',
  },
  {
    id: 99,
    value: 'New Zealand Standard Time',
    abbr: 'NZST',
    offset: 12,
    isdst: 0,
    text: '(UTC+12:00) Auckland, Wellington',
    utc: 'Antarctica/McMurdo',
  },
  {
    id: 100,
    value: 'UTC+12',
    abbr: 'U',
    offset: 12,
    isdst: 0,
    text: '(UTC+12:00) Coordinated Universal Time+12',
    utc: 'Etc/GMT-12',
  },
  {
    id: 101,
    value: 'Fiji Standard Time',
    abbr: 'FST',
    offset: 12,
    isdst: 0,
    text: '(UTC+12:00) Fiji',
    utc: 'Pacific/Fiji',
  },
  {
    id: 102,
    value: 'Magadan Standard Time',
    abbr: 'MST',
    offset: 12,
    isdst: 0,
    text: '(UTC+12:00) Magadan',
    utc: 'Asia/Anadyr',
  },
  {
    id: 103,
    value: 'Kamchatka Standard Time',
    abbr: 'KDT',
    offset: 13,
    isdst: 1,
    text: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old',
    utc: 'Asia/Kamchatka',
  },
  {
    id: 104,
    value: 'Tonga Standard Time',
    abbr: 'TST',
    offset: 13,
    isdst: 0,
    text: "(UTC+13:00) Nuku'alofa",
    utc: 'Etc/GMT-13',
  },
  {
    id: 105,
    value: 'Samoa Standard Time',
    abbr: 'SST',
    offset: 13,
    isdst: 0,
    text: '(UTC+13:00) Samoa',
    utc: 'Pacific/Apia',
  },
];
