export const Actions = {
  SET_SIDE_MENU: 'SET_SIDE_MENU',
  UPDATE_SELECTED_TRIP_DAY_ID: 'UPDATE_SELECTED_TRIP_DAY_ID',
  OPEN_TRIP_FORM: 'OPEN_TRIP_FORM',
  OPEN_TRIP_DAY_FORM: 'OPEN_TRIP_DAY_FORM',
  OPEN_TRIP_EVENT_FORM: 'OPEN_TRIP_EVENT_FORM',
  SET_EDIT_MODE: 'SET_EDIT_MODE',

  CLEAR_ALERT: 'CLEAR_ALERT',
  CREATE_ALERT: 'CREATE_ALERT',

  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  /** Fetching **/
  FETCHING_TRIP_LIST: 'FETCHING_TRIP_LIST',
  FETCHING_TRIP_LIST_SUCCESS: 'FETCHING_TRIP_LIST_SUCCESS',
  FETCHING_TRIP_LIST_FAILURE: 'FETCHING_TRIP_LIST_FAILURE',

  FETCHING_TRIP_DETAIL: 'FETCHING_TRIP_DETAIL',
  FETCHING_TRIP_DETAIL_SUCCESS: 'FETCHING_TRIP_DETAIL_SUCCESS',
  FETCHING_TRIP_DETAIL_FAILURE: 'FETCHING_TRIP_DETAIL_FAILURE',

  /** Creating **/
  CREATING_TRIP: 'CREATING_TRIP',
  CREATING_TRIP_SUCCESS: 'CREATING_TRIP_SUCCESS',
  CREATING_TRIP_FAILURE: 'CREATING_TRIP_FAILURE',

  CREATING_TRIP_DAY: 'CREATING_TRIP_DAY',
  CREATING_TRIP_DAY_SUCCESS: 'CREATING_TRIP_DAY_SUCCESS',
  CREATING_TRIP_DAY_FAILURE: 'CREATING_TRIP_DAY_FAILURE',

  CREATING_TRIP_EVENT: 'CREATING_TRIP_EVENT',
  CREATING_TRIP_EVENT_SUCCESS: 'CREATING_TRIP_EVENT_SUCCESS',
  CREATING_TRIP_EVENT_FAILURE: 'CREATING_TRIP_EVENT_FAILURE',

  /** Updating **/
  UPDATING_TRIP: 'UPDATING_TRIP',
  UPDATING_TRIP_SUCCESS: 'UPDATING_TRIP_SUCCESS',
  UPDATING_TRIP_FAILURE: 'UPDATING_TRIP_FAILURE',

  UPDATING_TRIP_DAY: 'UPDATING_TRIP_DAY',
  UPDATING_TRIP_DAY_SUCCESS: 'UPDATING_TRIP_DAY_SUCCESS',
  UPDATING_TRIP_DAY_FAILURE: 'UPDATING_TRIP_DAY_FAILURE',

  UPDATING_TRIP_EVENT: 'UPDATING_TRIP_EVENT',
  UPDATING_TRIP_EVENT_SUCCESS: 'UPDATING_TRIP_EVENT_SUCCESS',
  UPDATING_TRIP_EVENT_FAILURE: 'UPDATING_TRIP_EVENT_FAILURE',

  /** Deleting **/
  DELETING_TRIP_DAY: 'DELETING_TRIP_DAY',
  DELETING_TRIP_DAY_SUCCESS: 'DELETING_TRIP_DAY_SUCCESS',
  DELETING_TRIP_DAY_FAILURE: 'DELETING_TRIP_DAY_FAILURE',

  DELETING_TRIP_EVENT: 'DELETING_TRIP_EVENT',
  DELETING_TRIP_EVENT_SUCCESS: 'DELETING_TRIP_EVENT_SUCCESS',
  DELETING_TRIP_EVENT_FAILURE: 'DELETING_TRIP_EVENT_FAILURE',
};
